version: "3"

services:
   nasarobot:
      container_name: nasarobot
      build:
         args:
            - PORT=8080
            - SPRING_PROFILES_ACTIVE=prod
            - MEMORY_USE=
         dockerfile: ./Dockerfile
         context: ./nasarobot-api
      image: nasarobot
      restart: always
      environment:
         - SPRING_PROFILES_ACTIVE=prod
         - PORT=8080
      ports:
         - "8080:8080"
      expose:
         - 8080
      networks:
         - nasarobot-production-network

networks:
   nasarobot-production-network:
      driver: bridge

